# Generated by Django 5.1.4 on 2026-04-09 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('plenary', 'FATF Plenary'), ('webinar', 'Webinar'), ('training', 'Training'), ('workshop', 'Workshop'), ('egmont', 'EGMONT Meeting'), ('other', 'Other')], default='conference', max_length=15)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('is_virtual', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['start_date'],
            },
        ),
    ]
