# Generated by Django 5.1.4 on 2026-04-09 11:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypologyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('sector', models.CharField(choices=[('real_estate', 'Real Estate'), ('virtual_assets', 'Virtual Assets / Crypto'), ('trade_finance', 'Trade-Based Money Laundering'), ('banking', 'Banking'), ('insurance', 'Insurance'), ('cash_intensive', 'Cash-Intensive Business'), ('legal', 'Legal & Professional Services'), ('dnfbp', 'DNFBP'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('red_flags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typologies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'typology_cards',
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypologyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('typology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='typologies.typologycard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'typology_votes',
                'unique_together': {('user', 'typology')},
            },
        ),
    ]
