# Generated by Django 5.1.4 on 2026-04-09 11:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('fatf_status', models.CharField(choices=[('compliant', 'Largely Compliant'), ('partially', 'Partially Compliant'), ('non_compliant', 'Non-Compliant / Deficient'), ('enhanced', 'Enhanced Monitoring (Grey List)'), ('blacklisted', 'High-Risk (Black List)'), ('not_rated', 'Not Yet Rated')], default='not_rated', max_length=20)),
                ('fatf_region', models.CharField(blank=True, max_length=100)),
                ('last_evaluation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_evaluation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fiu_name', models.CharField(blank=True, max_length=300)),
                ('fiu_website', models.URLField(blank=True)),
                ('primary_legislation', models.TextField(blank=True)),
                ('aml_summary', models.TextField(blank=True)),
                ('key_risks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('mutual_evaluation_url', models.URLField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
    ]
