# Generated by Django 5.1.4 on 2026-04-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdictions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='egmont_member',
            field=models.BooleanField(default=False),
        ),
    ]
