# Generated by Django 5.1.4 on 2026-04-09 11:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('url_to_image', models.URLField(blank=True, max_length=1000)),
                ('source_name', models.CharField(max_length=200)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('sanctions', 'Sanctions'), ('fatf', 'FATF / FSRB'), ('regulatory', 'Regulatory Update'), ('enforcement', 'Enforcement Action'), ('crypto_aml', 'Crypto & Virtual Assets AML'), ('typology', 'Typology & Red Flags'), ('general', 'General Financial Crime')], default='general', max_length=20)),
                ('relevance_score', models.FloatField(db_index=True, default=0.0)),
                ('is_featured', models.BooleanField(default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_articles',
                'ordering': ['-published_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='news_articl_search__40d742_gin')],
            },
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('sanctions', 'Sanctions'), ('fatf', 'FATF'), ('aml', 'AML'), ('cft', 'CFT'), ('crypto_aml', 'Crypto AML'), ('enforcement', 'Enforcement'), ('regulatory', 'Regulatory'), ('typology', 'Typology')], max_length=30)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated custom keywords', max_length=500)),
                ('is_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert_subscriptions',
                'unique_together': {('user', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='SavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='news.newsarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_articles',
                'unique_together': {('user', 'article')},
            },
        ),
    ]
